In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree 
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
import joblib

In [2]:
df = pd.read_csv('career_pred.csv')

In [3]:
df.head()

Acedamic percentage in Operating Systems  percentage in Algorithms   
0                                        69                        63  \
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering   
0                                  78                                  87  \
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects   
0                               94                                  94  \
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics   
0                                   87                         84  \
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Hours working per day  ...   
0                                  61                      9  ...  \
1                                  91                     12  ...   
2                                  94                     11  ...   
3                                  69                      7  ...   
4                                  73                      4  ...   

   Interested Type of Books  Salary Range Expected  In a Realtionship?   
0              Prayer books                 salary                  no  \
1                 Childrens                 salary                 yes   
2                    Travel                   Work                  no   
3                   Romance                   Work                 yes   
4                 Cookbooks                 salary                  no   

   Gentle or Tuff behaviour? Management or Technical Salary/work   
0                   stubborn              Management      salary  \
1                     gentle               Technical      salary   
2                   stubborn              Management        work   
3                     gentle              Management        work   
4                   stubborn              Management        work   

  hard/smart worker worked in teams ever? Introvert   
0       hard worker                   yes        no  \
1       hard worker                    no       yes   
2       hard worker                    no       yes   
3      smart worker                   yes       yes   
4       hard worker                   yes       yes   

               Suggested Job Role  
0              Database Developer  
1            Portal Administrator  
2            Portal Administrator  
3  Systems Security Administrator  
4        Business Systems Analyst  

[5 rows x 39 columns]

In [4]:
df.dtypes

Acedamic percentage in Operating Systems     int64
percentage in Algorithms                     int64
Percentage in Programming Concepts           int64
Percentage in Software Engineering           int64
Percentage in Computer Networks              int64
Percentage in Electronics Subjects           int64
Percentage in Computer Architecture          int64
Percentage in Mathematics                    int64
Percentage in Communication skills           int64
Hours working per day                        int64
Logical quotient rating                      int64
hackathons                                   int64
coding skills rating                         int64
public speaking points                       int64
can work long time before system?           object
self-learning capability?                   object
Extra-courses did                           object
certifications                              object
workshops                                   object
talenttests taken?             

In [5]:
df = df.drop('Acedamic percentage in Operating Systems', axis=1)

In [6]:
df = df.drop('percentage in Algorithms', axis=1)

In [7]:
df = df.drop('Percentage in Programming Concepts', axis=1)

In [8]:
df = df.drop('Percentage in Software Engineering', axis=1)

In [9]:
df = df.drop('Percentage in Computer Networks', axis=1)

In [10]:
df = df.drop('Percentage in Electronics Subjects', axis=1)

In [11]:
df = df.drop('Percentage in Computer Architecture', axis=1)

In [12]:
df = df.drop('Percentage in Mathematics', axis=1)

In [13]:
df = df.drop('Percentage in Communication skills', axis=1)

In [14]:
df = df.drop('Logical quotient rating', axis=1)

In [15]:
df = df.drop('hackathons', axis=1)

In [16]:
df = df.drop('coding skills rating', axis=1)

In [17]:
df = df.drop('can work long time before system?', axis=1)

In [18]:
df = df.drop('certifications', axis=1)

In [19]:
df = df.drop('workshops', axis=1)

In [20]:
df = df.drop('talenttests taken?', axis=1)

In [21]:
df = df.drop('olympiads', axis=1)

In [22]:
df = df.drop('interested career area ', axis=1)

In [23]:
df = df.drop('Job/Higher Studies?', axis=1)

In [24]:
df = df.drop('Type of company want to settle in?', axis=1)

In [25]:
df = df.drop('Taken inputs from seniors or elders', axis=1)

In [26]:
df = df.drop('Salary Range Expected', axis=1)

In [27]:
df = df.drop('In a Realtionship?', axis=1)

In [28]:
df.head()

Hours working per day  public speaking points self-learning capability?   
0                      9                       8                       yes  \
1                     12                       3                        no   
2                     11                       3                        no   
3                      7                       5                       yes   
4                      4                       3                        no   

  Extra-courses did reading and writing skills memory capability score   
0               yes                  excellent               excellent  \
1               yes                       poor                  medium   
2               yes                       poor               excellent   
3                no                     medium               excellent   
4                no                       poor               excellent   

     Interested subjects interested in games Interested Type of Books   
0        cloud computing                  no             Prayer books  \
1               networks                 yes                Childrens   
2                hacking                 yes                   Travel   
3               networks                  no                  Romance   
4  Computer Architecture                 yes                Cookbooks   

  Gentle or Tuff behaviour? Management or Technical Salary/work   
0                  stubborn              Management      salary  \
1                    gentle               Technical      salary   
2                  stubborn              Management        work   
3                    gentle              Management        work   
4                  stubborn              Management        work   

  hard/smart worker worked in teams ever? Introvert   
0       hard worker                   yes        no  \
1       hard worker                    no       yes   
2       hard worker                    no       yes   
3      smart worker                   yes       yes   
4       hard worker                   yes       yes   

               Suggested Job Role  
0              Database Developer  
1            Portal Administrator  
2            Portal Administrator  
3  Systems Security Administrator  
4        Business Systems Analyst

In [29]:
df=df.dropna()
df.isna().sum().sum()

0

In [30]:
df.duplicated()
df.drop_duplicates()

Hours working per day  public speaking points   
0                          9                       8  \
1                         12                       3   
2                         11                       3   
3                          7                       5   
4                          4                       3   
...                      ...                     ...   
19995                      4                       8   
19996                      7                       8   
19997                      7                       3   
19998                      5                       5   
19999                      7                       6   

      self-learning capability? Extra-courses did reading and writing skills   
0                           yes               yes                  excellent  \
1                            no               yes                       poor   
2                            no               yes                       poor   
3                           yes                no                     medium   
4                            no                no                       poor   
...                         ...               ...                        ...   
19995                        no                no                       poor   
19996                        no                no                     medium   
19997                       yes               yes                     medium   
19998                        no                no                       poor   
19999                       yes               yes                  excellent   

      memory capability score    Interested subjects interested in games   
0                   excellent        cloud computing                  no  \
1                      medium               networks                 yes   
2                   excellent                hacking                 yes   
3                   excellent               networks                  no   
4                   excellent  Computer Architecture                 yes   
...                       ...                    ...                 ...   
19995               excellent   Software Engineering                 yes   
19996               excellent             Management                 yes   
19997               excellent               networks                 yes   
19998                    poor                    IOT                  no   
19999               excellent                    IOT                  no   

      Interested Type of Books Gentle or Tuff behaviour?   
0                 Prayer books                  stubborn  \
1                    Childrens                    gentle   
2                       Travel                  stubborn   
3                      Romance                    gentle   
4                    Cookbooks                  stubborn   
...                        ...                       ...   
19995                 Journals                  stubborn   
19996                Cookbooks                  stubborn   
19997                    Drama                    gentle   
19998                   Travel                    gentle   
19999                   Comics                    gentle   

      Management or Technical Salary/work hard/smart worker   
0                  Management      salary       hard worker  \
1                   Technical      salary       hard worker   
2                  Management        work       hard worker   
3                  Management        work      smart worker   
4                  Management        work       hard worker   
...                       ...         ...               ...   
19995              Management      salary      smart worker   
19996              Management      salary       hard worker   
19997               Technical        work       hard worker   
19998              Management        work      smart worker   
19999              Management        work     

In [31]:
df = df.drop_duplicates(subset=df.columns.difference(['Suggested Job Role']))

In [32]:
df.shape

(19996, 16)

In [33]:
df['Suggested Job Role'].nunique()

34

In [34]:
df['Suggested Job Role'].value_counts()

Suggested Job Role
Network Security Administrator               1112
Network Security Engineer                     630
Network Engineer                              621
Project Manager                               602
Database Administrator                        593
Portal Administrator                          592
Information Technology Manager                591
Software Engineer                             589
UX Designer                                   589
Design & UX                                   588
Software Developer                            587
CRM Business Analyst                          584
Business Systems Analyst                      582
Database Developer                            581
Solutions Architect                           577
Software Systems Engineer                     575
Software Quality Assurance (QA) / Testing     571
Database Manager                              570
Web Developer                                 570
CRM Technical Developer        

In [35]:
import random

def remove_random_rows(df, job_role, n_rows):
    matching_indices = df[df['Suggested Job Role'] == job_role].index
    if len(matching_indices) < n_rows:
        print(f"Error: There are only {len(matching_indices)} rows with the '{job_role}' job role. Cannot remove {n_rows} rows.")
        return df
    
    random_indices = random.sample(list(matching_indices), n_rows)
    df_dropped = df.drop(random_indices, inplace=False)
    
    return df_dropped

In [36]:
df = remove_random_rows(df, 'Network Security Administrator', 500)

In [37]:
df['Suggested Job Role'].value_counts()

Suggested Job Role
Network Security Engineer                    630
Network Engineer                             621
Network Security Administrator               612
Project Manager                              602
Database Administrator                       593
Portal Administrator                         592
Information Technology Manager               591
Software Engineer                            589
UX Designer                                  589
Design & UX                                  588
Software Developer                           587
CRM Business Analyst                         584
Business Systems Analyst                     582
Database Developer                           581
Solutions Architect                          577
Software Systems Engineer                    575
Software Quality Assurance (QA) / Testing    571
Database Manager                             570
Web Developer                                570
CRM Technical Developer                      567
T

In [38]:
df.shape

(19496, 16)

In [39]:
df['Hours working per day'].unique()

array([ 9, 12, 11,  7,  4,  6, 10,  8,  5])

In [40]:
df['public speaking points'].unique()

array([8, 3, 5, 1, 6, 4, 9, 7, 2])

In [41]:
df['self-learning capability?'].unique()

array(['yes', 'no'], dtype=object)

In [42]:
df['Extra-courses did'].unique()

array(['yes', 'no'], dtype=object)

In [43]:
df['reading and writing skills'].unique()

array(['excellent', 'poor', 'medium'], dtype=object)

In [44]:
df['memory capability score'].unique()

array(['excellent', 'medium', 'poor'], dtype=object)

In [45]:
df['Interested subjects'].unique()

array(['cloud computing', 'networks', 'hacking', 'Computer Architecture',
       'programming', 'parallel computing', 'IOT', 'data engineering',
       'Software Engineering', 'Management'], dtype=object)

In [46]:
df['interested in games'].unique()

array(['no', 'yes'], dtype=object)

In [47]:
df['Interested Type of Books'].unique()

array(['Prayer books', 'Childrens', 'Travel', 'Romance', 'Cookbooks',
       'Self help', 'Drama', 'Math', 'Religion-Spirituality', 'Anthology',
       'Trilogy', 'Autobiographies', 'Mystery', 'Diaries', 'Journals',
       'History', 'Art', 'Dictionaries', 'Horror', 'Encyclopedias',
       'Action and Adventure', 'Fantasy', 'Comics', 'Science fiction',
       'Series', 'Guide', 'Biographies', 'Health', 'Satire', 'Science',
       'Poetry'], dtype=object)

In [48]:
df['Gentle or Tuff behaviour?'].unique()

array(['stubborn', 'gentle'], dtype=object)

In [49]:
df['Management or Technical'].unique()

array(['Management', 'Technical'], dtype=object)

In [50]:
df['Salary/work'].unique()

array(['salary', 'work'], dtype=object)

In [51]:
df['hard/smart worker'].unique()

array(['hard worker', 'smart worker'], dtype=object)

In [52]:
df['worked in teams ever?'].unique()

array(['yes', 'no'], dtype=object)

In [53]:
df['Introvert'].unique()

array(['no', 'yes'], dtype=object)

In [54]:
col_list_obj = df.select_dtypes(include=['object']).columns.to_list()

In [55]:
col_list_obj

['self-learning capability?',
 'Extra-courses did',
 'reading and writing skills',
 'memory capability score',
 'Interested subjects',
 'interested in games',
 'Interested Type of Books',
 'Gentle or Tuff behaviour?',
 'Management or Technical',
 'Salary/work',
 'hard/smart worker',
 'worked in teams ever?',
 'Introvert',
 'Suggested Job Role']

In [56]:
def labelEncoding(df, columns):
    encoders = {}
    for col in columns:
        le = preprocessing.LabelEncoder().fit(df[col])
        df[col] = le.transform(df[col])
        encoders[col] = le
    return df, encoders

In [57]:
def label_encode_columns_w_fit_encoders(df, columns, encoders):
    for col in columns:
        le = encoders.get(col)
        df[col] = le.transform(df[col])
    return df

In [58]:
df, label_encoders = labelEncoding(df, col_list_obj)

In [59]:
df.head()

Hours working per day  public speaking points  self-learning capability?   
0                      9                       8                          1  \
1                     12                       3                          0   
2                     11                       3                          0   
3                      7                       5                          1   
4                      4                       3                          0   

   Extra-courses did  reading and writing skills  memory capability score   
0                  1                           0                        0  \
1                  1                           2                        1   
2                  1                           2                        0   
3                  0                           1                        0   
4                  0                           2                        0   

   Interested subjects  interested in games  Interested Type of Books   
0                    4                    0                        21  \
1                    7                    1                         5   
2                    6                    1                        29   
3                    7                    0                        23   
4                    0                    1                         7   

   Gentle or Tuff behaviour?  Management or Technical  Salary/work   
0                          1                        0            0  \
1                          0                        1            0   
2                          1                        0            1   
3                          0                        0            1   
4                          1                        0            1   

   hard/smart worker  worked in teams ever?  Introvert  Suggested Job Role  
0                  0                      1          0                   7  
1                  0                      0          1                  18  
2                  0                      0          1                  18  
3                  1                      1          1                  28  
4                  0                      1          1                   2

In [60]:
df.dtypes

Hours working per day         int64
public speaking points        int64
self-learning capability?     int64
Extra-courses did             int64
reading and writing skills    int64
memory capability score       int64
Interested subjects           int64
interested in games           int64
Interested Type of Books      int64
Gentle or Tuff behaviour?     int64
Management or Technical       int64
Salary/work                   int64
hard/smart worker             int64
worked in teams ever?         int64
Introvert                     int64
Suggested Job Role            int64
dtype: object

In [61]:
df.describe()

Hours working per day  public speaking points   
count           19496.000000            19496.000000  \
mean                7.983125                5.013182   
std                 2.593573                2.587416   
min                 4.000000                1.000000   
25%                 6.000000                3.000000   
50%                 8.000000                5.000000   
75%                10.000000                7.000000   
max                12.000000                9.000000   

       self-learning capability?  Extra-courses did   
count               19496.000000       19496.000000  \
mean                    0.504514           0.496769   
std                     0.499992           0.500002   
min                     0.000000           0.000000   
25%                     0.000000           0.000000   
50%                     1.000000           0.000000   
75%                     1.000000           1.000000   
max                     1.000000           1.000000   

       reading and writing skills  memory capability score   
count                19496.000000             19496.000000  \
mean                     0.997897                 0.999897   
std                      0.817885                 0.816476   
min                      0.000000                 0.000000   
25%                      0.000000                 0.000000   
50%                      1.000000                 1.000000   
75%                      2.000000                 2.000000   
max                      2.000000                 2.000000   

       Interested subjects  interested in games  Interested Type of Books   
count         19496.000000         19496.000000              19496.000000  \
mean              4.504668             0.498615                 15.218250   
std               2.872012             0.500011                  8.666487   
min               0.000000             0.000000                  0.000000   
25%               2.000000             0.000000                  8.000000   
50%               5.000000             0.000000                 15.000000   
75%               7.000000             1.000000                 23.000000   
max               9.000000             1.000000                 30.000000   

       Gentle or Tuff behaviour?  Management or Technical   Salary/work   
count               19496.000000             19496.000000  19496.000000  \
mean                    0.498205                 0.502872      0.495845   
std                     0.500010                 0.500005      0.499996   
min                     0.000000                 0.000000      0.000000   
25%                     0.000000                 0.000000      0.000000   
50%                     0.000000                 1.000000      0.000000   
75%                     1.000000                 1.000000      1.000000   
max                     1.000000                 1.000000      1.000000   

       hard/smart worker  worked in teams ever?     Introvert   
count       19496.000000           19496.000000  19496.000000  \
mean            0.501231               0.496256      0.504514   
std             0.500011               0.499999      0.499992   
min             0.000000               0.000000      0.000000   
25%             0.000000               0.000000      0.000000   
50%             1.000000               0.000000      1.000000   
75%             1.000000               1.000000      1.000000   
max             1.000000               1.000000      1.000000   

       Suggested Job Role  
count        19496.000000  
mean            16.515593  
std              9.761525  
min              0.000000  
25%              8.000000  
50%             17.000000  
75%             25.000000  
max             33.000000

In [62]:
X = df[df.columns.difference(['Suggested Job Role'])]
y = df['Suggested Job Role']

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [64]:
def pred_metrics(model, X_train, y_train, X_test, y_test):
    print('----- Train -----')
    y_pred_train = model.predict(X_train)
    print('Misclassified samples: {}'.format((y_train != y_pred_train).sum()))
    print('Accuracy: {:.2f}'.format(accuracy_score(y_train, y_pred_train)))
    print('Precision: {:.2f}'.format(precision_score(y_train, y_pred_train, average='weighted')))
    print('Recall: {:.2f}'.format(recall_score(y_train, y_pred_train, average='weighted')))
    print('F1: {:.2f}'.format(f1_score(y_train, y_pred_train, average='weighted')))
    
    print('\n----- Test -----')
    y_pred_test = model.predict(X_test)
    print('Misclassified samples: {}'.format((y_test != y_pred_test).sum()))
    print('Accuracy: {:.2f}'.format(accuracy_score(y_test, y_pred_test)))
    print('Precision: {:.2f}'.format(precision_score(y_test, y_pred_test, average='weighted')))
    print('Recall: {:.2f}'.format(recall_score(y_test, y_pred_test, average='weighted')))
    print('F1: {:.2f}'.format(f1_score(y_test, y_pred_test, average='weighted')))
    
    return y_pred_test

## Decision Tree

In [65]:
dectree = DecisionTreeClassifier(max_depth=5, max_leaf_nodes=17)
dectree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, max_leaf_nodes=17)

In [66]:
pred_metrics(dectree, X_train, y_train, X_test, y_test)

----- Train -----
Misclassified samples: 14913
Accuracy: 0.04
Precision: 0.02
Recall: 0.04
F1: 0.02

----- Test -----
Misclassified samples: 3776
Accuracy: 0.03
Precision: 0.01
Recall: 0.03
F1: 0.01


/Users/mane/Library/Python/3.9/lib/python/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/mane/Library/Python/3.9/lib/python/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([30,  3, 30, ...,  3, 16,  8])

## Support Vector Machine

In [67]:
svm_m = svm.SVC().fit(X_train, y_train)

In [68]:
pred_metrics(svm_m, X_train, y_train, X_test, y_test)

----- Train -----
Misclassified samples: 14941
Accuracy: 0.04
Precision: 0.06
Recall: 0.04
F1: 0.02

----- Test -----


/Users/mane/Library/Python/3.9/lib/python/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Misclassified samples: 3806
Accuracy: 0.02
Precision: 0.01
Recall: 0.02
F1: 0.01


/Users/mane/Library/Python/3.9/lib/python/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([20, 17, 31, ...,  8,  6, 23])

## Random Forest

In [69]:
rfc = RandomForestClassifier(n_estimators=100, max_depth=5, max_leaf_nodes=17, random_state=0)
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, max_leaf_nodes=17, random_state=0)

In [70]:
pred_metrics(rfc, X_train, y_train, X_test, y_test)

----- Train -----
Misclassified samples: 14047
Accuracy: 0.10
Precision: 0.22
Recall: 0.10
F1: 0.08

----- Test -----
Misclassified samples: 3778
Accuracy: 0.03
Precision: 0.02
Recall: 0.03
F1: 0.02


/Users/mane/Library/Python/3.9/lib/python/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([15, 23, 31, ..., 17, 13,  7])

## K-Nearest Neighbors

In [71]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [72]:
pred_metrics(knn, X_train, y_train, X_test, y_test)

----- Train -----
Misclassified samples: 11583
Accuracy: 0.26
Precision: 0.31
Recall: 0.26
F1: 0.22

----- Test -----
Misclassified samples: 3760
Accuracy: 0.04
Precision: 0.04
Recall: 0.04
F1: 0.03


array([5, 4, 0, ..., 1, 0, 4])

## Gradient Boosting 

In [73]:
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3)
gb.fit(X_train, y_train)

GradientBoostingClassifier()

In [74]:
pred_metrics(gb, X_train, y_train, X_test, y_test)

----- Train -----
Misclassified samples: 13104
Accuracy: 0.16
Precision: 0.16
Recall: 0.16
F1: 0.16

----- Test -----
Misclassified samples: 3787
Accuracy: 0.03
Precision: 0.03
Recall: 0.03
F1: 0.03


array([30, 23, 15, ..., 32, 13,  7])

## Choosing the best model

In [75]:
joblib.dump(gb, "best_model.joblib")

['best_model.joblib']

In [76]:
joblib.dump(label_encoders, "encoders.joblib")

['encoders.joblib']

## Testing

In [77]:
input_data = {'Hours working per day': 4,
 'public speaking points': 3,
 'self-learning capability?': 'no',
 'Extra-courses did': 'yes',
 'reading and writing skills': 'poor',
 'memory capability score': 'excellent',
 'Interested subjects': 'Computer Architecture',
 'interested in games': 'yes',
 'Interested Type of Books': 'Cookbooks',
 'Gentle or Tuff behaviour?': 'stubborn',
 'Management or Technical': 'Management',
 'Salary/work': 'work',
 'hard/smart worker': 'hard worker',
 'worked in teams ever?': 'yes',
 'Introvert': 'yes',
 'Suggested Job Role': 'Business Systems Analyst'}
input_data

{'Hours working per day': 4,
 'public speaking points': 3,
 'self-learning capability?': 'no',
 'Extra-courses did': 'yes',
 'reading and writing skills': 'poor',
 'memory capability score': 'excellent',
 'Interested subjects': 'Computer Architecture',
 'interested in games': 'yes',
 'Interested Type of Books': 'Cookbooks',
 'Gentle or Tuff behaviour?': 'stubborn',
 'Management or Technical': 'Management',
 'Salary/work': 'work',
 'hard/smart worker': 'hard worker',
 'worked in teams ever?': 'yes',
 'Introvert': 'yes',
 'Suggested Job Role': 'Business Systems Analyst'}

In [78]:
input_col_list = col_list_obj[:-1]

In [79]:
input_df = pd.DataFrame([input_data])
input_encoded = label_encode_columns_w_fit_encoders(df=input_df, columns=col_list_obj, encoders=label_encoders)
input_encoded

Hours working per day  public speaking points  self-learning capability?   
0                      4                       3                          0  \

   Extra-courses did  reading and writing skills  memory capability score   
0                  1                           2                        0  \

   Interested subjects  interested in games  Interested Type of Books   
0                    0                    1                         7  \

   Gentle or Tuff behaviour?  Management or Technical  Salary/work   
0                          1                        0            1  \

   hard/smart worker  worked in teams ever?  Introvert  Suggested Job Role  
0                  0                      1          1                   2

In [80]:
input = input_encoded[df.columns.difference(['Suggested Job Role'])]
input

Extra-courses did  Gentle or Tuff behaviour?  Hours working per day   
0                  1                          1                      4  \

   Interested Type of Books  Interested subjects  Introvert   
0                         7                    0          1  \

   Management or Technical  Salary/work  hard/smart worker   
0                        0            1                  0  \

   interested in games  memory capability score  public speaking points   
0                    1                        0                       3  \

   reading and writing skills  self-learning capability?   
0                           2                          0  \

   worked in teams ever?  
0                      1

In [81]:
model = joblib.load("best_model.joblib")
predicted_label = model.predict(input)
predicted_label

array([10])

In [82]:
def decode_label(column, label, encoders):
    le = encoders.get(column)
    decoded_label = le.inverse_transform([label])

    return decoded_label[0]

In [83]:
decoded_label = decode_label('Suggested Job Role', predicted_label[0], label_encoders)
decoded_label

'E-Commerce Analyst'